#!/bin/sh

BIN=./Stylesheets/bin

if [ ! -d $BIN ]; then
  git submodule init
  git submodule update
fi

mkdir -p dist

# Generate full ODD
$BIN/teitoodd --odd dracor.odd dist/dracor.odd.xml

# Transform to RNG
$BIN/teitorng --odd dist/dracor.odd.xml dist/dracor.rng
# Transform to Schematron
$BIN/teitoschematron --odd dist/dracor.odd.xml dist/dracor.sch
# Transform to HTML
$BIN/teitohtml --odd dist/dracor.odd.xml dist/dracor.html
