name: Generate release assets and deploy

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if this is a rerun
        id: is-rerun
        run: |
          if [[ "${{ github.run_attempt }}" -gt 1 ]]; then
            echo "is_rerun=true" >> $GITHUB_ENV
          else
            echo "is_rerun=false" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true

      - run: ./build

      - name: Upload RNG
        if: env.is_rerun == 'false'
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/dracor.rng
          asset_name: dracor-schema-${{ github.event.release.tag_name }}.rng
          asset_content_type: application/xml

      - name: Upload Schematron
        if: env.is_rerun == 'false'
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/dracor.sch
          asset_name: dracor-schema-${{ github.event.release.tag_name }}.sch
          asset_content_type: application/xml

      - name: Upload HTML
        if: env.is_rerun == 'false'
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/index.html
          asset_name: dracor-guidelines-${{ github.event.release.tag_name }}.html
          asset_content_type: text/html

      - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
        with:
          ssh-private-key: ${{ secrets.DRACOR_ORG_DEPLOY_KEY }}

      - name: Deploy schemas to staging and dev
        run: |
          scp -o StrictHostKeyChecking=no ./dist/dracor.rng ${{ secrets.DRACOR_ORG_DEPLOY_USER }}@staging.dracor.org:/var/www/html/schema.rng
          scp -o StrictHostKeyChecking=no ./dist/dracor.sch ${{ secrets.DRACOR_ORG_DEPLOY_USER }}@staging.dracor.org:/var/www/html/dracor.sch
          scp -o StrictHostKeyChecking=no ./dist/dracor.rng ${{ secrets.DRACOR_ORG_DEPLOY_USER }}@dev.dracor.org:/var/www/html/schema.rng
          scp -o StrictHostKeyChecking=no ./dist/dracor.sch ${{ secrets.DRACOR_ORG_DEPLOY_USER }}@dev.dracor.org:/var/www/html/dracor.sch

      - name: Deploy schemas to production
        if: ${{ ! github.event.release.prerelease }}
        run: |
          scp -o StrictHostKeyChecking=no ./dist/dracor.rng ${{ secrets.DRACOR_ORG_DEPLOY_USER }}@dracor.org:/var/www/html/schema.rng
          scp -o StrictHostKeyChecking=no ./dist/dracor.sch ${{ secrets.DRACOR_ORG_DEPLOY_USER }}@dracor.org:/var/www/html/dracor.sch

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: dist/

  # There are environment rules that restrict which tags can deploy to the
  # github-pages environment, see
  # https://github.com/dracor-org/dracor-schema/settings/environments/5489677481/edit
  deploy:
    if: ${{ ! github.event.release.prerelease }}
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
