name: Generate release assets

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build_assets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if this is a rerun
        id: is-rerun
        run: |
          if [[ "${{ github.run_attempt }}" -gt 1 ]]; then
            echo "is_rerun=true" >> $GITHUB_ENV
          else
            echo "is_rerun=false" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      - run: ./build

      - name: Upload RNG
        if: env.is_rerun == 'false'
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/dracor.rng
          asset_name: dracor-schema-${{ github.event.release.tag_name }}.rng
          asset_content_type: application/xml

      - name: Upload Schematron
        if: env.is_rerun == 'false'
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/dracor.sch
          asset_name: dracor-schema-${{ github.event.release.tag_name }}.sch
          asset_content_type: application/xml

      - name: Upload HTML
        if: env.is_rerun == 'false'
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/dracor.html
          asset_name: dracor-schema-${{ github.event.release.tag_name }}.html
          asset_content_type: text/html

      - uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387 # v0.9.0
        with:
          ssh-private-key: ${{ secrets.DRACOR_ORG_DEPLOY_KEY }}

      - name: Deploy to staging and dev
        run: |
          scp -o StrictHostKeyChecking=no ./dist/dracor.html ${{ secrets.DRACOR_ORG_DEPLOY_USER }}@staging.dracor.org:/var/www/html/odd.html
          scp -o StrictHostKeyChecking=no ./dist/dracor.rng ${{ secrets.DRACOR_ORG_DEPLOY_USER }}@staging.dracor.org:/var/www/html/schema.rng
          scp -o StrictHostKeyChecking=no ./dist/dracor.sch ${{ secrets.DRACOR_ORG_DEPLOY_USER }}@staging.dracor.org:/var/www/html/dracor.sch
          scp -o StrictHostKeyChecking=no ./dist/dracor.html ${{ secrets.DRACOR_ORG_DEPLOY_USER }}@dev.dracor.org:/var/www/html/odd.html
          scp -o StrictHostKeyChecking=no ./dist/dracor.rng ${{ secrets.DRACOR_ORG_DEPLOY_USER }}@dev.dracor.org:/var/www/html/schema.rng
          scp -o StrictHostKeyChecking=no ./dist/dracor.sch ${{ secrets.DRACOR_ORG_DEPLOY_USER }}@dev.dracor.org:/var/www/html/dracor.sch

      - name: Deploy to production
        if: ${{ ! github.event.release.prerelease }}
        run: |
          scp -o StrictHostKeyChecking=no ./dist/dracor.html ${{ secrets.DRACOR_ORG_DEPLOY_USER }}@dracor.org:/var/www/html/odd.html
          scp -o StrictHostKeyChecking=no ./dist/dracor.rng ${{ secrets.DRACOR_ORG_DEPLOY_USER }}@dracor.org:/var/www/html/schema.rng
          scp -o StrictHostKeyChecking=no ./dist/dracor.sch ${{ secrets.DRACOR_ORG_DEPLOY_USER }}@dracor.org:/var/www/html/dracor.sch
